"""schema inicial: as nove tabelas da secao 7

Revision ID: 10c39ad670de
Revises: 
Create Date: 2026-09-12 20:49:16.624791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c39ad670de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("plan <> ''", name='ck_tenants_plan_nao_vazio'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('credentials_ref', sa.String(length=512), nullable=True),
    sa.Column('driver_pref', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("driver_pref in ('manual','youtube-api','aggregator','browser')", name='ck_accounts_driver_pref'),
    sa.CheckConstraint("platform in ('youtube','tiktok','instagram')", name='ck_accounts_platform'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_accounts_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'platform', 'handle', name='uq_accounts_tenant_platform_handle')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_accounts_tenant_id_id', ['tenant_id', 'id'], unique=True)

    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("adapter in ('youtube','youtube-channel','twitch-vod','twitch-live','gdrive','upload')", name='ck_sources_adapter'),
    sa.CheckConstraint('duration_ms is null or duration_ms >= 0', name='ck_sources_duration_nao_negativa'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_sources_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_sources_tenant_id_id', ['tenant_id', 'id'], unique=True)

    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_templates_version_positiva'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_templates_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_templates_tenant_name_version')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_templates_tenant_id_id', ['tenant_id', 'id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("role in ('owner','editor','viewer')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_users_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_users_tenant_id_id', ['tenant_id', 'id'], unique=True)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('timings_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("stage in ('ingest', 'probe', 'transcribe', 'detect', 'reframe', 'compose', 'publish')", name='ck_jobs_stage'),
    sa.CheckConstraint("status in ('queued', 'running', 'completed', 'failed')", name='ck_jobs_status'),
    sa.ForeignKeyConstraint(['tenant_id', 'source_id'], ['sources.tenant_id', 'sources.id'], name='fk_jobs_source', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_jobs_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_jobs_tenant_id_id', ['tenant_id', 'id'], unique=True)
        batch_op.create_index('ix_jobs_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('start_word_idx', sa.Integer(), nullable=False),
    sa.Column('end_word_idx', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rubric_json', sa.JSON(), nullable=True),
    sa.Column('render_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('end_word_idx > start_word_idx', name='ck_clips_fim_depois_do_inicio'),
    sa.CheckConstraint('score is null or (score >= 0 and score <= 100)', name='ck_clips_score_0_100'),
    sa.CheckConstraint('start_word_idx >= 0', name='ck_clips_start_nao_negativo'),
    sa.ForeignKeyConstraint(['tenant_id', 'job_id'], ['jobs.tenant_id', 'jobs.id'], name='fk_clips_job', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_clips_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clips_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_clips_tenant_id_id', ['tenant_id', 'id'], unique=True)
        batch_op.create_index('ix_clips_tenant_job', ['tenant_id', 'job_id'], unique=False)

    op.create_table('publications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clip_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('driver', sa.String(length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('remote_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("driver in ('manual', 'youtube-api', 'aggregator', 'browser')", name='ck_publications_driver'),
    sa.CheckConstraint("status in ('scheduled', 'publishing', 'published', 'failed', 'cancelled')", name='ck_publications_status'),
    sa.ForeignKeyConstraint(['tenant_id', 'account_id'], ['accounts.tenant_id', 'accounts.id'], name='fk_publications_account', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'clip_id'], ['clips.tenant_id', 'clips.id'], name='fk_publications_clip', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_publications_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'clip_id', 'account_id', name='uq_publications_tenant_clip_account')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_publications_tenant_id_id', ['tenant_id', 'id'], unique=True)
        batch_op.create_index('ix_publications_tenant_status_scheduled', ['tenant_id', 'status', 'scheduled_at'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('retention_pct', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('retention_pct is null or (retention_pct >= 0 and retention_pct <= 100)', name='ck_metrics_retention_0_100'),
    sa.CheckConstraint('views is null or views >= 0', name='ck_metrics_views_nao_negativa'),
    sa.ForeignKeyConstraint(['tenant_id', 'publication_id'], ['publications.tenant_id', 'publications.id'], name='fk_metrics_publication', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_metrics_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'publication_id', 'collected_at', name='uq_metrics_tenant_publication_collected')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_metrics_tenant_id_id', ['tenant_id', 'id'], unique=True)
        batch_op.create_index('ix_metrics_tenant_publication', ['tenant_id', 'publication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_metrics_tenant_publication')
        batch_op.drop_index('ix_metrics_tenant_id_id')
        batch_op.drop_index(batch_op.f('ix_metrics_tenant_id'))

    op.drop_table('metrics')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index('ix_publications_tenant_status_scheduled')
        batch_op.drop_index('ix_publications_tenant_id_id')
        batch_op.drop_index(batch_op.f('ix_publications_tenant_id'))

    op.drop_table('publications')
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index('ix_clips_tenant_job')
        batch_op.drop_index('ix_clips_tenant_id_id')
        batch_op.drop_index(batch_op.f('ix_clips_tenant_id'))

    op.drop_table('clips')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_tenant_status')
        batch_op.drop_index('ix_jobs_tenant_id_id')
        batch_op.drop_index(batch_op.f('ix_jobs_tenant_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_tenant_id_id')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index('ix_templates_tenant_id_id')
        batch_op.drop_index(batch_op.f('ix_templates_tenant_id'))

    op.drop_table('templates')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('ix_sources_tenant_id_id')
        batch_op.drop_index(batch_op.f('ix_sources_tenant_id'))

    op.drop_table('sources')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_tenant_id_id')
        batch_op.drop_index(batch_op.f('ix_accounts_tenant_id'))

    op.drop_table('accounts')
    op.drop_table('tenants')
    # ### end Alembic commands ###
